"""
Herion Practice Catalog — Definitive Foundation
38 procedures across 5 categories with universal flow model.
Each official procedure includes: flow_definition, official_entry_point,
expected_release, tracking_mode, and real entity URLs.
"""


def build_internal(pid, name, desc, category, agents, docs=None, doc_specs=None, approval=False, explanation=""):
    """Helper for internal support procedures (no official action, no entity)."""
    CATEGORY_LABELS = {"informativo": "Informativo", "documentale": "Documentale", "lavoro": "Lavoro"}
    return {
        "practice_id": pid,
        "name": name,
        "description": desc,
        "category": category,
        "category_label": CATEGORY_LABELS.get(category, category.capitalize()),
        "procedure_type": "internal_support",
        "user_type": ["private", "freelancer", "company"],
        "country_scope": "IT",
        "operational_status": "active_internal",
        "scope_note": "Servizio interno di piattaforma.",
        "risk_level": "basic",
        "support_level": "supported",
        "expected_channel": "email",
        "destination_type": "user_communication",
        "required_documents": docs or [],
        "document_specs": doc_specs or [],
        "official_action": None,
        "flow_definition": None,
        "who_acts": {
            "herion_prepares": True,
            "herion_submits": category == "informativo",
            "user_submits": False,
            "user_signs": False,
            "delegation_possible": False,
            "entity_response_expected": False,
        },
        "auth_method": None,
        "proof_expected": None,
        "estimated_duration": {"label": "Immediato", "min_days": 0, "max_days": 1},
        "delegation_required": False,
        "approval_required": approval,
        "agents": agents,
        "blocking_conditions": [],
        "escalation_conditions": [],
        "next_step": "Prossima azione",
        "user_explanation": explanation or desc,
    }


def build_official(
    pid, name, desc, category, entity_name, action_code, action_label, action_desc,
    form_ref, entry_url, auth_method, user_type, agents,
    docs, doc_specs,
    proof_type, proof_label, proof_timing,
    tracking_type, tracking_label, tracking_ref,
    duration_label, min_days, max_days,
    herion_submits=False, user_signs=False, delegation_possible=False,
    delegation_required=False, risk_level="medium",
    blocking=None, escalation=None, explanation="",
    url_verified=True, destination_type="tax_authority",
):
    """Helper for official procedures with full flow model."""
    CATEGORY_LABELS = {"fiscale": "Fiscale", "previdenziale": "Previdenziale", "societario": "Societario", "lavoro": "Lavoro"}
    return {
        "practice_id": pid,
        "name": name,
        "description": desc,
        "category": category,
        "category_label": CATEGORY_LABELS.get(category, category.capitalize()),
        "procedure_type": "official_procedure",
        "user_type": user_type,
        "country_scope": "IT",
        "operational_status": "active_italy_scope",
        "scope_note": f"Procedura ufficiale. Ente: {entity_name}.",
        "risk_level": risk_level,
        "support_level": "supported",
        "expected_channel": "official_portal",
        "destination_type": destination_type,
        "required_documents": docs,
        "document_specs": doc_specs,
        "official_action": {
            "code": action_code,
            "label": action_label,
            "description": action_desc,
            "entity_name": entity_name,
            "form_reference": form_ref,
        },
        "flow_definition": {
            "practice_type": pid,
            "target_entity": entity_name,
            "target_direction": action_label,
            "user_action_required": not herion_submits,
            "document_collection_required": len(docs) > 0,
            "document_verification_required": len(docs) > 0,
            "official_entry_point": {
                "type": "portal" if entry_url else "manual_upload",
                "label": f"Portale {entity_name} - {action_label}",
                "url": entry_url,
                "url_verified": url_verified,
                "auth_required": auth_method is not None,
                "auth_method": auth_method,
            },
            "expected_release": {
                "type": proof_type,
                "label": proof_label,
                "timing": proof_timing,
            },
            "tracking_mode": {
                "type": tracking_type,
                "label": tracking_label,
                "route_or_reference": tracking_ref,
            },
        },
        "who_acts": {
            "herion_prepares": True,
            "herion_submits": herion_submits,
            "user_submits": not herion_submits,
            "user_signs": user_signs,
            "delegation_possible": delegation_possible,
            "entity_response_expected": True,
        },
        "auth_method": auth_method,
        "proof_expected": {
            "type": proof_type,
            "timing": proof_timing,
            "label": proof_label,
            "optional": False,
        },
        "estimated_duration": {"label": duration_label, "min_days": min_days, "max_days": max_days},
        "delegation_required": delegation_required,
        "approval_required": True,
        "agents": agents,
        "blocking_conditions": blocking or [],
        "escalation_conditions": escalation or [],
        "next_step": f"Preparazione {action_label.lower()}",
        "user_explanation": explanation or desc,
    }


# ── DOCUMENT SPEC HELPERS ──
DS_ID = {"key": "identity", "name": "Documento di identita", "why_needed": "Obbligatorio per identificazione presso l'ente", "format": "PDF o immagine (fronte/retro)", "mandatory": True}
DS_CF = {"key": "tax_declarations", "name": "Codice fiscale / tessera sanitaria", "why_needed": "Per associare la pratica al codice fiscale", "format": "PDF o immagine", "mandatory": True}
DS_PIVA = {"key": "tax_declarations", "name": "Partita IVA attiva", "why_needed": "Numero P.IVA attivo necessario per la procedura", "format": "Visura o certificato P.IVA", "mandatory": True}
DS_ACCOUNTING = {"key": "accounting", "name": "Dati contabili / importi", "why_needed": "Per calcolare correttamente codici tributo e importi", "format": "PDF o foglio di calcolo", "mandatory": True}
DS_VAT_REGS = {"key": "vat_documents", "name": "Registri IVA", "why_needed": "Base per il calcolo IVA a debito/credito", "format": "PDF o export contabile", "mandatory": True}
DS_INVOICES = {"key": "invoices", "name": "Fatture emesse e ricevute", "why_needed": "Per la riconciliazione con i registri", "format": "PDF o XML", "mandatory": True}
DS_COMPANY = {"key": "company_documents", "name": "Visura camerale e atto costitutivo", "why_needed": "Per verificare lo stato della societa", "format": "PDF", "mandatory": True}
DS_BALANCE = {"key": "accounting", "name": "Bilancio", "why_needed": "Per la verifica della situazione patrimoniale", "format": "PDF firmato", "mandatory": True}
DS_TAX = {"key": "tax", "name": "Certificazione debiti tributari", "why_needed": "Per confermare l'assenza di debiti verso l'erario", "format": "PDF", "mandatory": True}
DS_COMPLIANCE = {"key": "compliance", "name": "Dichiarazione di conformita", "why_needed": "Per attestare il rispetto degli obblighi di legge", "format": "PDF firmato", "mandatory": True}
DS_PAYROLL = {"key": "payroll", "name": "Dati retributivi dipendenti", "why_needed": "Per il calcolo dei contributi e delle certificazioni", "format": "PDF o foglio di calcolo", "mandatory": True}
DS_CONTRACT = {"key": "company_documents", "name": "Contratto o accordo", "why_needed": "Documento contrattuale richiesto per la procedura", "format": "PDF firmato", "mandatory": True}
DS_PREV_DECL = {"key": "tax_declarations", "name": "Dichiarazioni precedenti", "why_needed": "Per verifica e continuita con gli anni precedenti", "format": "PDF", "mandatory": False}
DS_PROPERTY = {"key": "activity", "name": "Dati immobiliari / catastali", "why_needed": "Necessari per imposte sugli immobili o successioni", "format": "Visura catastale PDF", "mandatory": True}
DS_EMPLOYEE = {"key": "payroll", "name": "Dati anagrafici e contrattuali del lavoratore", "why_needed": "Per comunicazione obbligatoria e gestione rapporto", "format": "PDF o modulo compilato", "mandatory": True}
DS_WORK_CONTRACT = {"key": "payroll", "name": "Contratto di lavoro", "why_needed": "Tipologia contrattuale e condizioni del rapporto", "format": "PDF firmato", "mandatory": True}
DS_STATUTO = {"key": "company_documents", "name": "Statuto societario", "why_needed": "Per verificare clausole e poteri degli organi sociali", "format": "PDF", "mandatory": True}
DS_ASSEMBLY = {"key": "company_documents", "name": "Verbale assemblea", "why_needed": "Delibera assembleare necessaria per la procedura", "format": "PDF firmato", "mandatory": True}

# Real official URLs (verified where possible)
URL_ADE_TELEMATICI = "https://telematici.agenziaentrate.gov.it"
URL_ADE_FISCONLINE = "https://telematici.agenziaentrate.gov.it/Abilitazione/Fisconline.jsp"
URL_ADE_CASSETTO = "https://telematici.agenziaentrate.gov.it/Abilitazione/Cassetto.jsp"
URL_ADE_F24WEB = "https://telematici.agenziaentrate.gov.it/F24web"
URL_ADE_FATTURE = "https://ivaservizi.agenziaentrate.gov.it/portale/"
URL_ADE_PRECOMPILATA = "https://infoprecompilata.agenziaentrate.gov.it"
URL_ADE_REDDITI = "https://telematici.agenziaentrate.gov.it/Abilitazione/ReddOnLine.jsp"
URL_INPS_SERVIZI = "https://www.inps.it/prestazioni-servizi"
URL_INPS_MYINPS = "https://myinps2.inps.it"
URL_REGISTRO_IMPRESE = "https://www.registroimprese.it"
URL_COMUNICA_STARWEB = "https://starweb.infocamere.it"
URL_SUAP = None  # Varies by municipality
URL_AGENZIA_DOGANE = "https://www.adm.gov.it"
URL_ADE_SUCCESSIONI = "https://telematici.agenziaentrate.gov.it/SuccessioniWeb"
URL_ADE_CONTRATTI = "https://telematici.agenziaentrate.gov.it/Abilitazione/RLI.jsp"
URL_ADE_CIVIS = "https://telematici.agenziaentrate.gov.it/Abilitazione/Civis.jsp"
URL_INPS_UNIEMENS = "https://www.inps.it/prestazioni-servizi"  # UniEmens via servizi INPS
URL_INAIL_SERVIZI = "https://www.inail.it/cs/internet/attivita/assicurazione.html"
URL_TELEMACO = "https://telemaco.infocamere.it"  # Deposito bilanci CCIAA


def get_catalog_entries():
    """Return all catalog entries — Batch 1 expansion (~80 procedures)."""
    entries = []

    # ══════════════════════════════════════
    # INFORMATIVO (internal support) — 4
    # ══════════════════════════════════════
    entries.append(build_internal("INFO_FISCAL_GENERIC", "Richiesta informazioni fiscali generiche", "Richiesta di chiarimenti su adempimenti fiscali di base.", "informativo", ["intake", "research", "advisor"], explanation="Richiesta di informazioni fiscali di base. Herion raccoglie la domanda e fornisce indicazioni chiare."))
    entries.append(build_internal("INFO_REGIME_FORFETTARIO", "Informazioni regime forfettario", "Chiarimenti su requisiti, limiti e vantaggi del regime forfettario.", "informativo", ["research", "advisor"], explanation="Spiegazione chiara del regime forfettario: requisiti, limiti di fatturato, aliquote e vantaggi."))
    entries.append(build_internal("PRACTICE_FOLLOWUP", "Promemoria e follow-up pratica", "Promemoria sullo stato di avanzamento di una pratica.", "informativo", ["monitor", "deadline", "advisor"], explanation="Ricevi aggiornamenti e promemoria sullo stato della tua pratica."))
    entries.append(build_internal("STATUS_UPDATE", "Aggiornamento stato pratica", "Comunicazione di aggiornamento sullo stato della pratica.", "informativo", ["monitor", "advisor"], explanation="Ricevi un riepilogo aggiornato sullo stato della tua pratica."))

    # ══════════════════════════════════════
    # DOCUMENTALE (internal support) — 7
    # ══════════════════════════════════════
    entries.append(build_internal("DOC_MISSING_REQUEST", "Richiesta documenti mancanti", "Notifica all'utente sui documenti necessari per procedere.", "documentale", ["documents", "flow", "advisor"], explanation="Ti indichiamo quali documenti servono per completare la tua pratica."))
    entries.append(build_internal("DOC_PRELIMINARY_SEND", "Invio documenti preliminari", "Invio di documentazione preliminare a un destinatario.", "documentale", ["documents", "routing", "advisor"], docs=["identity"], doc_specs=[DS_ID], approval=True, explanation="Preparazione e invio della documentazione preliminare."))
    entries.append(build_internal("BLOCKED_RECOVERY", "Recupero pratica bloccata", "Recupero di una pratica in stato bloccato.", "documentale", ["flow", "monitor", "documents"], explanation="Identifichiamo cosa blocca la pratica e ti guidiamo nella risoluzione."))
    entries.append(build_internal("DOSSIER_DELIVERY", "Consegna dossier finale", "Consegna del fascicolo completo della pratica.", "documentale", ["documents", "advisor"], approval=True, explanation="Il fascicolo completo della pratica viene preparato e consegnato."))
    entries.append(build_internal("DOC_COMPLETENESS", "Verifica completezza documenti", "Controllo che tutti i documenti necessari siano presenti.", "documentale", ["documents", "flow"], explanation="Verifichiamo che tutti i documenti necessari siano stati caricati."))
    entries.append(build_internal("USER_APPROVAL_REQ", "Richiesta approvazione utente", "Richiesta di approvazione esplicita prima di procedere.", "documentale", ["flow", "monitor"], approval=True, explanation="Prima di procedere, ti chiediamo di verificare e approvare il riepilogo."))
    entries.append(build_internal("PDF_REPORT_DELIVERY", "Consegna PDF/report finale", "Generazione e consegna del report PDF finale.", "documentale", ["documents", "advisor"], explanation="Il report finale della pratica viene generato e messo a disposizione."))

    # ══════════════════════════════════════
    # FISCALE (official procedures) — 14
    # ══════════════════════════════════════
    entries.append(build_official("VAT_OPEN_PF", "Apertura Partita IVA persone fisiche", "Preparazione della pratica di apertura P.IVA per individui e freelance.", "fiscale", "Agenzia delle Entrate", "apertura_partita_iva_pf", "Apertura Partita IVA", "Invio del modello AA9/12 all'Agenzia delle Entrate per l'apertura della Partita IVA", "Modello AA9/12", URL_ADE_FISCONLINE, "SPID", ["freelancer"], ["intake", "research", "routing", "documents", "flow"], ["identity", "tax_declarations"], [DS_ID, DS_CF], "protocol_number", "Numero di protocollo rilasciato dal portale", "immediate", "portal_status", "Verifica stato sul portale AdE", URL_ADE_CASSETTO, "3-5 giorni lavorativi", 3, 5, blocking=["documenti identita mancanti", "codice fiscale mancante"], escalation=["struttura societaria complessa"], explanation="Ti guidiamo nella preparazione della pratica di apertura P.IVA. Herion prepara il modello AA9/12, tu lo invii sul portale con SPID."))

    entries.append(build_official("VAT_VARIATION_PF", "Variazione Partita IVA persone fisiche", "Modifica dei dati della partita IVA per persone fisiche.", "fiscale", "Agenzia delle Entrate", "variazione_partita_iva_pf", "Variazione dati Partita IVA", "Invio variazione tramite modello AA9/12", "Modello AA9/12", URL_ADE_FISCONLINE, "SPID", ["freelancer"], ["research", "routing", "documents", "flow"], ["identity"], [DS_ID], "protocol_number", "Numero di protocollo della variazione", "immediate", "portal_status", "Verifica stato sul cassetto fiscale", URL_ADE_CASSETTO, "2-4 giorni lavorativi", 2, 4, blocking=["partita IVA non attiva"], explanation="Preparazione della variazione dei dati della tua P.IVA."))

    entries.append(build_official("VAT_CLOSURE_PF", "Chiusura Partita IVA persone fisiche", "Chiusura della partita IVA.", "fiscale", "Agenzia delle Entrate", "chiusura_partita_iva_pf", "Chiusura Partita IVA", "Invio della cessazione tramite modello AA9/12", "Modello AA9/12", URL_ADE_FISCONLINE, "SPID", ["freelancer"], ["research", "routing", "documents", "flow", "delegate"], ["identity", "tax_declarations"], [DS_ID, DS_CF], "protocol_number", "Numero di protocollo della cessazione", "immediate", "portal_status", "Verifica stato cassetto fiscale", URL_ADE_CASSETTO, "5-10 giorni lavorativi", 5, 10, delegation_possible=True, blocking=["debiti pendenti non verificati"], escalation=["pendenze fiscali complesse"], explanation="Ti guidiamo nella chiusura della P.IVA, verificando pendenze e requisiti."))

    entries.append(build_official("F24_PREPARATION", "Preparazione e validazione F24", "Compilazione e verifica del modello F24.", "fiscale", "Agenzia delle Entrate", "compilazione_f24", "Compilazione modello F24", "Preparazione del modello F24 per pagamento imposte, contributi e tributi", "Modello F24", URL_ADE_F24WEB, "SPID", ["private", "freelancer", "company"], ["ledger", "documents", "compliance", "advisor"], ["accounting"], [DS_ACCOUNTING], "payment_receipt", "Quietanza di pagamento F24", "immediate", "receipt_verification", "Verifica quietanza", URL_ADE_CASSETTO, "1-2 giorni lavorativi", 1, 2, destination_type="tax_payment", blocking=["dati contabili insufficienti"], explanation="Prepariamo e verifichiamo il modello F24 per i tuoi pagamenti fiscali."))

    entries.append(build_official("F24_WEB", "Supporto F24 Web", "Compilazione F24 tramite portale web.", "fiscale", "Agenzia delle Entrate", "invio_f24_web", "Invio F24 tramite portale web", "Compilazione e invio del modello F24 tramite servizio F24 Web", "F24 Web", URL_ADE_F24WEB, "SPID", ["private", "freelancer", "company"], ["routing", "research", "ledger", "flow"], ["accounting"], [DS_ACCOUNTING], "portal_confirmation", "Conferma invio dal portale F24 Web", "immediate", "portal_status", "Verifica sul portale F24 Web", URL_ADE_F24WEB, "1-2 giorni lavorativi", 1, 2, destination_type="tax_payment", explanation="Ti guidiamo nell'uso del portale F24 Web. Herion prepara i dati, tu compili e invii."))

    entries.append(build_official("VAT_DECLARATION", "Dichiarazione IVA annuale", "Preparazione e invio della dichiarazione IVA.", "fiscale", "Agenzia delle Entrate", "invio_dichiarazione_iva", "Invio dichiarazione IVA", "Invio della dichiarazione IVA annuale tramite il portale", "Dichiarazione IVA annuale", URL_ADE_TELEMATICI, "SPID", ["freelancer", "company"], ["research", "documents", "compliance", "flow"], ["vat_documents", "invoices", "accounting"], [DS_VAT_REGS, DS_INVOICES, DS_ACCOUNTING], "protocol_number", "Ricevuta telematica AdE", "delayed", "portal_status", "Verifica ricevuta nel cassetto fiscale", URL_ADE_CASSETTO, "5-10 giorni lavorativi", 5, 10, user_signs=True, delegation_possible=True, blocking=["registri IVA incompleti"], escalation=["operazioni intracomunitarie complesse"], explanation="Prepariamo la tua dichiarazione IVA verificando registri e documenti. Tu la firmi e la invii."))

    entries.append(build_official("EINVOICING", "Fatturazione elettronica SDI", "Emissione e gestione fatture elettroniche tramite SDI.", "fiscale", "Agenzia delle Entrate (SDI)", "emissione_fattura_elettronica", "Emissione fattura elettronica via SDI", "Generazione e invio della fattura tramite il Sistema di Interscambio", "Formato FatturaPA / FatturaB2B", URL_ADE_FATTURE, "SPID", ["freelancer", "company"], ["research", "routing", "documents", "advisor"], ["invoices"], [DS_INVOICES], "portal_confirmation", "Notifica di esito dal SDI", "delayed", "portal_status", "Verifica esito su Fatture e Corrispettivi", URL_ADE_FATTURE, "1-3 giorni lavorativi", 1, 3, delegation_possible=True, explanation="Ti supportiamo nella gestione della fatturazione elettronica tramite SDI."))

    entries.append(build_official("INCOME_TAX_PF", "Dichiarazione Redditi PF", "Compilazione e invio del Modello Redditi Persone Fisiche.", "fiscale", "Agenzia delle Entrate", "invio_redditi_pf", "Invio Modello Redditi PF", "Compilazione e trasmissione telematica del Modello Redditi Persone Fisiche", "Modello Redditi PF", URL_ADE_REDDITI, "SPID", ["freelancer"], ["research", "ledger", "documents", "compliance", "flow"], ["identity", "tax_declarations", "accounting"], [DS_ID, DS_CF, DS_ACCOUNTING], "protocol_number", "Ricevuta telematica dichiarazione redditi", "delayed", "portal_status", "Verifica ricevuta nel cassetto fiscale", URL_ADE_CASSETTO, "10-20 giorni lavorativi", 10, 20, user_signs=True, delegation_possible=True, blocking=["dati reddituali incompleti"], escalation=["redditi esteri", "plusvalenze complesse"], explanation="Prepariamo la tua dichiarazione dei redditi. Herion compila, tu verifichi e invii."))

    entries.append(build_official("INCOME_TAX_730", "Dichiarazione 730 precompilata", "Accesso e invio della dichiarazione 730 precompilata.", "fiscale", "Agenzia delle Entrate", "invio_730_precompilata", "Invio 730 precompilata", "Accesso alla dichiarazione 730 precompilata e trasmissione telematica", "Modello 730", URL_ADE_PRECOMPILATA, "SPID", ["private", "freelancer"], ["research", "advisor", "documents"], ["identity"], [DS_ID], "protocol_number", "Ricevuta invio 730 precompilata", "immediate", "portal_status", "Verifica stato su precompilata", URL_ADE_PRECOMPILATA, "1-5 giorni lavorativi", 1, 5, explanation="Ti guidiamo nell'accesso e invio della 730 precompilata. Herion verifica, tu invii con SPID."))

    entries.append(build_official("LIPE_QUARTERLY", "Comunicazione Liquidazioni IVA (LIPE)", "Invio trimestrale delle liquidazioni periodiche IVA.", "fiscale", "Agenzia delle Entrate", "invio_lipe", "Comunicazione LIPE trimestrale", "Trasmissione telematica delle liquidazioni periodiche IVA", "Comunicazione LIPE", URL_ADE_TELEMATICI, "SPID", ["freelancer", "company"], ["ledger", "compliance", "documents", "flow"], ["vat_documents", "accounting"], [DS_VAT_REGS, DS_ACCOUNTING], "protocol_number", "Ricevuta telematica LIPE", "delayed", "portal_status", "Verifica ricevuta nel cassetto fiscale", URL_ADE_CASSETTO, "3-7 giorni lavorativi", 3, 7, user_signs=True, delegation_possible=True, blocking=["registri IVA del trimestre incompleti"], explanation="Prepariamo la comunicazione trimestrale delle liquidazioni IVA (LIPE)."))

    entries.append(build_official("CU_CERTIFICATION", "Certificazione Unica (CU)", "Preparazione e invio della Certificazione Unica.", "fiscale", "Agenzia delle Entrate", "invio_certificazione_unica", "Invio Certificazione Unica", "Compilazione e trasmissione della CU per redditi di lavoro dipendente e assimilati", "Certificazione Unica (CU)", URL_ADE_TELEMATICI, "SPID", ["company"], ["documents", "compliance", "ledger", "flow"], ["payroll", "accounting"], [DS_PAYROLL, DS_ACCOUNTING], "protocol_number", "Ricevuta telematica CU", "delayed", "portal_status", "Verifica ricevuta nel cassetto fiscale", URL_ADE_CASSETTO, "5-15 giorni lavorativi", 5, 15, user_signs=True, delegation_possible=True, blocking=["dati retributivi mancanti"], explanation="Prepariamo la Certificazione Unica (CU) per i tuoi dipendenti o collaboratori."))

    entries.append(build_official("INTRASTAT", "Modelli Intrastat", "Preparazione e invio dei modelli Intrastat per operazioni intracomunitarie.", "fiscale", "Agenzia delle Dogane", "invio_intrastat", "Invio modelli Intrastat", "Trasmissione telematica dei modelli Intrastat per cessioni/acquisti intracomunitari", "Modelli INTRA", URL_AGENZIA_DOGANE, "SPID", ["freelancer", "company"], ["research", "ledger", "documents", "compliance"], ["invoices", "vat_documents"], [DS_INVOICES, DS_VAT_REGS], "protocol_number", "Ricevuta telematica Intrastat", "delayed", "portal_status", "Verifica su portale Dogane", URL_AGENZIA_DOGANE, "3-10 giorni lavorativi", 3, 10, user_signs=True, delegation_possible=True, blocking=["fatture intracomunitarie incomplete"], escalation=["operazioni triangolari complesse"], explanation="Prepariamo i modelli Intrastat per le tue operazioni intracomunitarie."))

    entries.append(build_official("CASSETTO_FISCALE", "Consultazione cassetto fiscale", "Accesso e consultazione del cassetto fiscale.", "fiscale", "Agenzia delle Entrate", "consultazione_cassetto_fiscale", "Consultazione cassetto fiscale", "Accesso al cassetto fiscale per verifica dichiarazioni, versamenti e comunicazioni", None, URL_ADE_CASSETTO, "SPID", ["private", "freelancer", "company"], ["research", "advisor", "monitor"], [], [], "portal_confirmation", "Visualizzazione dati nel cassetto fiscale", "immediate", "portal_status", "Consultazione diretta sul portale", URL_ADE_CASSETTO, "Immediato (accesso online)", 0, 1, risk_level="basic", explanation="Ti aiutiamo a consultare e comprendere il tuo cassetto fiscale."))

    entries.append(build_official("VISURA_CAMERALE", "Richiesta visura camerale", "Richiesta e scaricamento della visura camerale.", "fiscale", "Camera di Commercio", "richiesta_visura", "Richiesta visura camerale", "Accesso al Registro Imprese per ottenere la visura camerale aggiornata", None, URL_REGISTRO_IMPRESE, None, ["freelancer", "company"], ["research", "documents"], [], [], "receipt_pdf", "Visura camerale scaricata", "immediate", "receipt_verification", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "Immediato", 0, 1, risk_level="basic", destination_type="chamber_registry", explanation="Ti aiutiamo a ottenere la visura camerale aggiornata dal Registro Imprese."))

    # ══════════════════════════════════════
    # PREVIDENZIALE (official procedures) — 5
    # ══════════════════════════════════════
    entries.append(build_official("INPS_GESTIONE_SEP", "Iscrizione Gestione Separata INPS", "Iscrizione alla Gestione Separata INPS per liberi professionisti.", "previdenziale", "INPS", "iscrizione_gestione_separata", "Iscrizione Gestione Separata", "Iscrizione alla Gestione Separata per liberi professionisti senza cassa", "Modulo iscrizione online", URL_INPS_SERVIZI, "SPID", ["freelancer"], ["research", "routing", "documents", "flow"], ["identity", "tax_declarations"], [DS_ID, DS_PIVA], "protocol_number", "Conferma iscrizione dall'area riservata INPS", "immediate", "portal_status", "Verifica su MyINPS", URL_INPS_MYINPS, "3-7 giorni lavorativi", 3, 7, destination_type="social_security", blocking=["partita IVA non attiva"], explanation="Ti guidiamo nell'iscrizione alla Gestione Separata INPS."))

    entries.append(build_official("INPS_CASSETTO", "Consultazione cassetto previdenziale", "Consultazione del cassetto previdenziale INPS.", "previdenziale", "INPS", "consultazione_cassetto_previdenziale", "Consultazione cassetto previdenziale", "Accesso al cassetto previdenziale sul portale INPS", None, URL_INPS_MYINPS, "SPID", ["freelancer"], ["research", "routing", "advisor", "monitor"], [], [], "portal_confirmation", "Visualizzazione dati previdenziali", "immediate", "portal_status", "Consultazione su MyINPS", URL_INPS_MYINPS, "Immediato (accesso online)", 0, 1, risk_level="basic", destination_type="social_security", explanation="Ti aiutiamo a consultare e comprendere il tuo cassetto previdenziale INPS."))

    entries.append(build_official("INPS_DURC", "Richiesta DURC", "Richiesta del Documento Unico di Regolarita Contributiva.", "previdenziale", "INPS", "richiesta_durc", "Richiesta DURC online", "Richiesta del DURC tramite il portale INPS per attestare la regolarita contributiva", None, URL_INPS_SERVIZI, "SPID", ["freelancer", "company"], ["research", "documents", "flow"], ["identity"], [DS_ID], "receipt_pdf", "DURC in formato PDF", "delayed", "portal_status", "Verifica stato richiesta su MyINPS", URL_INPS_MYINPS, "5-15 giorni lavorativi", 5, 15, destination_type="social_security", blocking=["irregolarita contributive"], explanation="Ti guidiamo nella richiesta del DURC per attestare la tua regolarita contributiva."))

    entries.append(build_official("INPS_ARTIGIANI", "Iscrizione Gestione Artigiani INPS", "Iscrizione alla Gestione Artigiani presso INPS.", "previdenziale", "INPS", "iscrizione_gestione_artigiani", "Iscrizione Gestione Artigiani", "Iscrizione alla gestione previdenziale per artigiani", "Modulo iscrizione artigiani", URL_INPS_SERVIZI, "SPID", ["freelancer"], ["research", "routing", "documents", "flow"], ["identity", "tax_declarations", "company_documents"], [DS_ID, DS_PIVA, DS_COMPANY], "protocol_number", "Conferma iscrizione Gestione Artigiani", "delayed", "portal_status", "Verifica su MyINPS", URL_INPS_MYINPS, "5-10 giorni lavorativi", 5, 10, destination_type="social_security", blocking=["iscrizione Camera di Commercio mancante"], explanation="Ti guidiamo nell'iscrizione alla Gestione Artigiani INPS."))

    entries.append(build_official("INPS_COMMERCIANTI", "Iscrizione Gestione Commercianti INPS", "Iscrizione alla Gestione Commercianti presso INPS.", "previdenziale", "INPS", "iscrizione_gestione_commercianti", "Iscrizione Gestione Commercianti", "Iscrizione alla gestione previdenziale per commercianti", "Modulo iscrizione commercianti", URL_INPS_SERVIZI, "SPID", ["freelancer", "company"], ["research", "routing", "documents", "flow"], ["identity", "tax_declarations", "company_documents"], [DS_ID, DS_PIVA, DS_COMPANY], "protocol_number", "Conferma iscrizione Gestione Commercianti", "delayed", "portal_status", "Verifica su MyINPS", URL_INPS_MYINPS, "5-10 giorni lavorativi", 5, 10, destination_type="social_security", blocking=["iscrizione Camera di Commercio mancante"], explanation="Ti guidiamo nell'iscrizione alla Gestione Commercianti INPS."))

    # ══════════════════════════════════════
    # SOCIETARIO (official procedures) — 5
    # ══════════════════════════════════════
    entries.append(build_official("COMPANY_CLOSURE", "Chiusura societaria post-liquidazione", "Gestione completa della chiusura societaria dopo liquidazione.", "societario", "Camera di Commercio", "cancellazione_registro_imprese", "Cancellazione dal Registro delle Imprese", "Deposito della domanda di cancellazione presso la Camera di Commercio", "Modulo S3 / ComUnica", URL_COMUNICA_STARWEB, "SPID", ["company"], ["intake", "research", "deadline", "flow", "routing", "delegate", "documents", "compliance", "ledger"], ["company_documents", "accounting", "identity", "tax", "compliance"], [DS_COMPANY, DS_BALANCE, DS_ID, DS_TAX, DS_COMPLIANCE], "protocol_number", "Numero protocollo Registro delle Imprese", "delayed", "portal_status", "Verifica stato su Registro Imprese", URL_REGISTRO_IMPRESE, "10-30 giorni lavorativi", 10, 30, user_signs=True, delegation_possible=True, delegation_required=True, destination_type="chamber_registry", blocking=["liquidazione non completata", "bilancio finale non approvato"], escalation=["contenziosi pendenti"], explanation="Herion prepara il percorso di chiusura post-liquidazione. Verifichiamo requisiti, raccogliamo documenti e prepariamo il dossier."))

    entries.append(build_official("COMPANY_FORMATION_SRL", "Costituzione SRL", "Avvio del processo di costituzione di una SRL.", "societario", "Camera di Commercio", "iscrizione_srl", "Iscrizione SRL al Registro Imprese", "Deposito dell'atto costitutivo e iscrizione al Registro delle Imprese", "ComUnica / Atto notarile", URL_COMUNICA_STARWEB, "SPID", ["company"], ["intake", "research", "documents", "compliance", "flow", "routing"], ["company_documents", "identity", "accounting"], [DS_COMPANY, DS_ID, {"key": "accounting", "name": "Capitale sociale versato", "why_needed": "Prova del versamento del capitale sociale", "format": "Bonifico o attestazione bancaria", "mandatory": True}], "protocol_number", "Numero iscrizione Registro Imprese", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "15-30 giorni lavorativi", 15, 30, user_signs=True, delegation_possible=True, delegation_required=True, destination_type="chamber_registry", blocking=["atto notarile mancante", "capitale non versato"], escalation=["struttura societaria complessa"], explanation="Ti accompagniamo nella costituzione della SRL, dalla preparazione dei documenti all'iscrizione al Registro Imprese."))

    entries.append(build_official("COMPANY_VARIATION", "Variazione dati Camera di Commercio", "Modifica dei dati aziendali presso il Registro Imprese.", "societario", "Camera di Commercio", "variazione_registro_imprese", "Variazione dati Registro Imprese", "Deposito della pratica di variazione dati presso la Camera di Commercio", "ComUnica", URL_COMUNICA_STARWEB, "SPID", ["company"], ["research", "documents", "flow", "routing"], ["company_documents", "identity"], [DS_COMPANY, DS_ID], "protocol_number", "Numero protocollo variazione", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "5-15 giorni lavorativi", 5, 15, destination_type="chamber_registry", explanation="Prepariamo la variazione dei dati aziendali presso la Camera di Commercio."))

    entries.append(build_official("SUAP_SCIA", "SCIA - Segnalazione Certificata Inizio Attivita", "Presentazione della SCIA allo sportello SUAP del Comune.", "societario", "SUAP / Comune", "presentazione_scia", "Presentazione SCIA", "Presentazione della Segnalazione Certificata di Inizio Attivita allo sportello SUAP", "Modulo SCIA", URL_SUAP, "SPID", ["freelancer", "company"], ["research", "documents", "compliance", "flow"], ["identity", "company_documents"], [DS_ID, DS_COMPANY], "protocol_number", "Numero protocollo SCIA", "immediate", "portal_status", "Verifica stato sul portale SUAP", None, "1-5 giorni lavorativi", 1, 5, destination_type="public_portal", url_verified=False, blocking=["requisiti tecnici non verificati"], explanation="Ti guidiamo nella presentazione della SCIA allo sportello SUAP del tuo Comune."))

    entries.append(build_official("ATECO_VARIATION", "Variazione codice ATECO", "Modifica del codice attivita economica (ATECO).", "societario", "Camera di Commercio / Agenzia delle Entrate", "variazione_ateco", "Variazione codice ATECO", "Comunicazione di variazione del codice ATECO tramite ComUnica e portale AdE", "ComUnica + AA9/12", URL_COMUNICA_STARWEB, "SPID", ["freelancer", "company"], ["research", "routing", "documents", "flow"], ["identity"], [DS_ID], "protocol_number", "Numero protocollo variazione ATECO", "delayed", "portal_status", "Verifica su Registro Imprese e cassetto fiscale", URL_REGISTRO_IMPRESE, "5-10 giorni lavorativi", 5, 10, destination_type="chamber_registry", explanation="Prepariamo la variazione del codice ATECO presso Camera di Commercio e Agenzia delle Entrate."))

    # ══════════════════════════════════════════════════════════════
    # BATCH 1 EXPANSION — NEW PROCEDURES (35 → ~80)
    # ══════════════════════════════════════════════════════════════

    # ── FISCALE: +10 new (14 → 24) ──

    entries.append(build_official("MOD_770", "Dichiarazione Modello 770", "Compilazione e invio del Modello 770 per sostituti d'imposta.", "fiscale", "Agenzia delle Entrate", "invio_modello_770", "Invio Modello 770", "Trasmissione telematica del Modello 770 con dati di ritenute operate", "Modello 770", URL_ADE_TELEMATICI, "SPID", ["company"], ["research", "ledger", "documents", "compliance", "flow"], ["payroll", "accounting"], [DS_PAYROLL, DS_ACCOUNTING], "protocol_number", "Ricevuta telematica Modello 770", "delayed", "portal_status", "Verifica ricevuta nel cassetto fiscale", URL_ADE_CASSETTO, "5-15 giorni lavorativi", 5, 15, user_signs=True, delegation_possible=True, blocking=["dati ritenute incompleti"], explanation="Prepariamo il Modello 770 per la dichiarazione delle ritenute operate come sostituto d'imposta."))

    entries.append(build_official("IRAP_DECLARATION", "Dichiarazione IRAP", "Compilazione e invio della dichiarazione IRAP.", "fiscale", "Agenzia delle Entrate", "invio_dichiarazione_irap", "Invio dichiarazione IRAP", "Trasmissione telematica della dichiarazione annuale IRAP", "Modello IRAP", URL_ADE_TELEMATICI, "SPID", ["freelancer", "company"], ["research", "ledger", "compliance", "documents", "flow"], ["accounting"], [DS_ACCOUNTING], "protocol_number", "Ricevuta telematica IRAP", "delayed", "portal_status", "Verifica ricevuta nel cassetto fiscale", URL_ADE_CASSETTO, "5-15 giorni lavorativi", 5, 15, user_signs=True, delegation_possible=True, blocking=["dati valore produzione incompleti"], explanation="Prepariamo la dichiarazione IRAP verificando il valore della produzione netta."))

    entries.append(build_official("RAVVEDIMENTO", "Ravvedimento operoso", "Regolarizzazione spontanea di omessi o tardivi versamenti.", "fiscale", "Agenzia delle Entrate", "ravvedimento_operoso", "Ravvedimento operoso", "Calcolo e versamento delle sanzioni ridotte per regolarizzazione spontanea tramite F24", "Modello F24 (ravvedimento)", URL_ADE_F24WEB, "SPID", ["private", "freelancer", "company"], ["research", "ledger", "compliance", "advisor"], ["accounting"], [DS_ACCOUNTING], "payment_receipt", "Quietanza F24 ravvedimento", "immediate", "receipt_verification", "Verifica quietanza nel cassetto fiscale", URL_ADE_CASSETTO, "1-3 giorni lavorativi", 1, 3, destination_type="tax_payment", explanation="Ti aiutiamo a calcolare e versare le sanzioni ridotte per regolarizzare la tua posizione fiscale."))

    entries.append(build_official("IVA_RIMBORSO", "Richiesta rimborso IVA", "Presentazione istanza di rimborso credito IVA.", "fiscale", "Agenzia delle Entrate", "richiesta_rimborso_iva", "Richiesta rimborso IVA", "Presentazione dell'istanza di rimborso del credito IVA annuale o infrannuale", "Modello IVA TR / Dichiarazione IVA", URL_ADE_TELEMATICI, "SPID", ["freelancer", "company"], ["research", "ledger", "documents", "compliance", "flow"], ["vat_documents", "accounting"], [DS_VAT_REGS, DS_ACCOUNTING], "protocol_number", "Ricevuta istanza rimborso", "delayed", "portal_status", "Verifica stato rimborso nel cassetto fiscale", URL_ADE_CASSETTO, "30-90 giorni lavorativi", 30, 90, risk_level="high", user_signs=True, delegation_possible=True, blocking=["credito IVA non verificato"], escalation=["importi superiori a 30.000 euro richiedono garanzia"], explanation="Prepariamo la richiesta di rimborso del credito IVA. Herion verifica il credito e prepara la documentazione."))

    entries.append(build_official("CONTRATTO_LOCAZIONE", "Registrazione contratto di locazione", "Registrazione di contratto di affitto presso AdE.", "fiscale", "Agenzia delle Entrate", "registrazione_contratto_locazione", "Registrazione contratto", "Registrazione telematica del contratto di locazione tramite modello RLI", "Modello RLI", URL_ADE_CONTRATTI, "SPID", ["private", "freelancer", "company"], ["research", "documents", "flow"], ["identity", "activity"], [DS_ID, DS_PROPERTY], "protocol_number", "Ricevuta registrazione contratto", "immediate", "portal_status", "Verifica su cassetto fiscale", URL_ADE_CASSETTO, "1-3 giorni lavorativi", 1, 3, explanation="Ti guidiamo nella registrazione del contratto di locazione tramite il portale dell'Agenzia delle Entrate."))

    entries.append(build_official("CEDOLARE_SECCA", "Opzione cedolare secca", "Esercizio dell'opzione per il regime di cedolare secca sugli affitti.", "fiscale", "Agenzia delle Entrate", "opzione_cedolare_secca", "Opzione cedolare secca", "Comunicazione dell'opzione per la cedolare secca contestualmente alla registrazione del contratto", "Modello RLI (opzione)", URL_ADE_CONTRATTI, "SPID", ["private", "freelancer"], ["research", "documents", "advisor"], ["identity", "activity"], [DS_ID, DS_PROPERTY], "protocol_number", "Conferma opzione cedolare secca", "immediate", "portal_status", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "1-3 giorni lavorativi", 1, 3, explanation="Ti aiutiamo a scegliere e comunicare l'opzione per la cedolare secca sugli affitti."))

    entries.append(build_official("IMU_TASI", "Calcolo e versamento IMU", "Supporto al calcolo e versamento dell'IMU.", "fiscale", "Comune di residenza", "calcolo_versamento_imu", "Calcolo e versamento IMU", "Calcolo dell'imposta municipale unica e versamento tramite F24", "Modello F24 (IMU)", URL_ADE_F24WEB, "SPID", ["private", "freelancer", "company"], ["research", "ledger", "advisor"], ["activity"], [DS_PROPERTY], "payment_receipt", "Quietanza F24 IMU", "immediate", "receipt_verification", "Verifica pagamento", None, "1-2 giorni lavorativi", 1, 2, destination_type="tax_payment", url_verified=False, explanation="Calcoliamo l'importo IMU dovuto e prepariamo il modello F24 per il versamento."))

    entries.append(build_official("DICHIARAZIONE_SUCCESSIONE", "Dichiarazione di successione", "Presentazione della dichiarazione di successione all'AdE.", "fiscale", "Agenzia delle Entrate", "dichiarazione_successione", "Dichiarazione di successione", "Compilazione e trasmissione telematica della dichiarazione di successione", "Dichiarazione di successione telematica", URL_ADE_SUCCESSIONI, "SPID", ["private"], ["intake", "research", "documents", "compliance", "flow"], ["identity", "activity", "accounting"], [DS_ID, DS_PROPERTY, {"key": "accounting", "name": "Documentazione patrimoniale del de cuius", "why_needed": "Per la determinazione dell'asse ereditario", "format": "PDF, visure, estratti conto", "mandatory": True}], "protocol_number", "Ricevuta dichiarazione di successione", "delayed", "portal_status", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "15-30 giorni lavorativi", 15, 30, risk_level="high", user_signs=True, blocking=["documentazione patrimoniale incompleta", "certificato di morte mancante"], escalation=["patrimoni complessi", "eredi residenti all'estero"], explanation="Ti accompagniamo nella preparazione della dichiarazione di successione, raccogliendo tutta la documentazione necessaria."))

    entries.append(build_official("INTERPELLO_ADE", "Interpello all'Agenzia delle Entrate", "Presentazione di interpello ordinario all'AdE.", "fiscale", "Agenzia delle Entrate", "presentazione_interpello", "Presentazione interpello", "Redazione e invio dell'istanza di interpello per ottenere un parere preventivo dall'AdE", "Istanza di interpello", URL_ADE_CIVIS, "SPID", ["freelancer", "company"], ["research", "advisor", "documents", "flow"], ["identity", "tax_declarations"], [DS_ID, DS_CF], "protocol_number", "Numero protocollo interpello", "delayed", "portal_status", "Verifica stato su cassetto fiscale", URL_ADE_CASSETTO, "60-120 giorni lavorativi", 60, 120, risk_level="high", url_verified=False, explanation="Ti guidiamo nella preparazione dell'istanza di interpello. Herion redige il quesito, tu lo invii."))

    entries.append(build_official("RATEIZZAZIONE_CARTELLE", "Rateizzazione cartelle esattoriali", "Richiesta di rateizzazione di cartelle di pagamento.", "fiscale", "Agenzia delle Entrate Riscossione", "richiesta_rateizzazione", "Richiesta rateizzazione", "Presentazione dell'istanza di rateizzazione per cartelle esattoriali", "Istanza di rateizzazione", None, "SPID", ["private", "freelancer", "company"], ["research", "documents", "compliance", "advisor"], ["identity", "accounting"], [DS_ID, DS_ACCOUNTING], "protocol_number", "Numero piano di rateizzazione", "delayed", "portal_status", "Verifica stato rateizzazione", None, "10-30 giorni lavorativi", 10, 30, risk_level="high", url_verified=False, blocking=["importo debito non determinato"], explanation="Ti aiutiamo a richiedere la rateizzazione delle cartelle esattoriali, preparando la documentazione necessaria."))

    # ── PREVIDENZIALE: +7 new (5 → 12) ──

    entries.append(build_official("INPS_UNIEMENS", "Denuncia UniEmens mensile", "Invio della denuncia contributiva mensile UniEmens.", "previdenziale", "INPS", "invio_uniemens", "Invio UniEmens", "Trasmissione telematica della denuncia contributiva mensile dei lavoratori", "Flusso UniEmens", URL_INPS_UNIEMENS, "SPID", ["company"], ["ledger", "documents", "compliance", "flow"], ["payroll"], [DS_PAYROLL], "protocol_number", "Ricevuta UniEmens", "immediate", "portal_status", "Verifica su MyINPS", URL_INPS_MYINPS, "Entro il 16 del mese successivo", 1, 5, destination_type="social_security", blocking=["dati retributivi mensili mancanti"], explanation="Prepariamo la denuncia UniEmens mensile per i contributi dei tuoi dipendenti."))

    entries.append(build_official("INPS_F24_CONTRIB", "F24 contributi previdenziali", "Versamento contributi INPS tramite F24.", "previdenziale", "INPS", "versamento_contributi_f24", "Versamento contributi INPS", "Calcolo e versamento dei contributi previdenziali tramite modello F24", "Modello F24 (contributi)", URL_ADE_F24WEB, "SPID", ["freelancer", "company"], ["ledger", "compliance", "advisor"], ["accounting"], [DS_ACCOUNTING], "payment_receipt", "Quietanza F24 contributi", "immediate", "receipt_verification", "Verifica nel cassetto previdenziale", URL_INPS_MYINPS, "1-2 giorni lavorativi", 1, 2, destination_type="social_security", explanation="Calcoliamo i contributi previdenziali dovuti e prepariamo il modello F24 per il versamento."))

    entries.append(build_official("INPS_MATERNITA", "Domanda maternita/paternita INPS", "Presentazione domanda di congedo maternita o paternita.", "previdenziale", "INPS", "domanda_maternita", "Domanda congedo maternita/paternita", "Presentazione telematica della domanda di congedo di maternita o paternita obbligatorio", "Domanda online INPS", URL_INPS_SERVIZI, "SPID", ["freelancer", "company"], ["research", "documents", "flow"], ["identity", "payroll"], [DS_ID, DS_EMPLOYEE], "protocol_number", "Conferma domanda maternita", "delayed", "portal_status", "Verifica stato su MyINPS", URL_INPS_MYINPS, "10-30 giorni lavorativi", 10, 30, destination_type="social_security", explanation="Ti guidiamo nella presentazione della domanda di congedo di maternita o paternita all'INPS."))

    entries.append(build_official("INPS_NASPI", "Domanda NASpI", "Presentazione domanda di indennita di disoccupazione NASpI.", "previdenziale", "INPS", "domanda_naspi", "Domanda NASpI", "Presentazione telematica della domanda di indennita NASpI entro 68 giorni dalla cessazione", "Domanda NASpI online", URL_INPS_SERVIZI, "SPID", ["private", "freelancer"], ["research", "documents", "flow", "advisor"], ["identity", "payroll"], [DS_ID, DS_EMPLOYEE], "protocol_number", "Conferma domanda NASpI", "delayed", "portal_status", "Verifica stato su MyINPS", URL_INPS_MYINPS, "15-30 giorni lavorativi", 15, 30, destination_type="social_security", blocking=["documentazione rapporto di lavoro mancante"], explanation="Ti guidiamo nella presentazione della domanda NASpI per l'indennita di disoccupazione."))

    entries.append(build_official("INAIL_AUTOLIQ", "Autoliquidazione INAIL", "Calcolo e versamento premio annuale INAIL.", "previdenziale", "INAIL", "autoliquidazione_inail", "Autoliquidazione INAIL", "Calcolo del premio INAIL e versamento tramite F24 entro il 16 febbraio", "Modulo autoliquidazione", URL_INAIL_SERVIZI, "SPID", ["company"], ["ledger", "compliance", "documents", "flow"], ["payroll", "accounting"], [DS_PAYROLL, DS_ACCOUNTING], "payment_receipt", "Quietanza versamento INAIL", "immediate", "receipt_verification", "Verifica su portale INAIL", URL_INAIL_SERVIZI, "Entro il 16 febbraio", 1, 5, destination_type="social_security", url_verified=False, blocking=["dati retributivi anno precedente mancanti"], explanation="Calcoliamo il premio INAIL annuale e prepariamo il versamento tramite F24."))

    entries.append(build_official("INAIL_DENUNCIA", "Denuncia infortunio INAIL", "Denuncia di infortunio sul lavoro all'INAIL.", "previdenziale", "INAIL", "denuncia_infortunio", "Denuncia infortunio", "Compilazione e invio telematico della denuncia di infortunio sul lavoro", "Denuncia infortunio online", URL_INAIL_SERVIZI, "SPID", ["company"], ["documents", "compliance", "flow"], ["payroll"], [DS_EMPLOYEE], "protocol_number", "Numero protocollo denuncia infortunio", "immediate", "portal_status", "Verifica su portale INAIL", URL_INAIL_SERVIZI, "Entro 2 giorni dall'evento", 0, 2, risk_level="high", destination_type="social_security", url_verified=False, blocking=["dati infortunio non completi"], explanation="Ti aiutiamo a compilare e inviare la denuncia di infortunio all'INAIL nei tempi previsti."))

    entries.append(build_official("INPS_COLF_BADANTI", "Gestione contributi colf e badanti", "Iscrizione e versamento contributi per lavoro domestico.", "previdenziale", "INPS", "gestione_colf_badanti", "Gestione lavoro domestico", "Comunicazione di assunzione e versamento trimestrale contributi per colf e badanti", "Portale lavoro domestico INPS", URL_INPS_SERVIZI, "SPID", ["private"], ["research", "documents", "flow", "advisor"], ["identity"], [DS_ID, DS_EMPLOYEE], "protocol_number", "Conferma iscrizione lavoro domestico", "immediate", "portal_status", "Verifica su MyINPS", URL_INPS_MYINPS, "3-10 giorni lavorativi", 3, 10, destination_type="social_security", explanation="Ti guidiamo nell'iscrizione e nella gestione dei contributi per colf, badanti e lavoro domestico."))

    # ── SOCIETARIO: +8 new (5 → 13) ──

    entries.append(build_official("VAT_OPEN_SOCIETA", "Apertura P.IVA societa", "Apertura della partita IVA per societa di persone o capitali.", "societario", "Agenzia delle Entrate", "apertura_piva_societa", "Apertura P.IVA Societa", "Invio del modello AA7/10 per l'apertura della P.IVA societaria tramite ComUnica", "Modello AA7/10 / ComUnica", URL_COMUNICA_STARWEB, "SPID", ["company"], ["intake", "research", "routing", "documents", "flow"], ["company_documents", "identity"], [DS_COMPANY, DS_ID], "protocol_number", "Numero protocollo apertura P.IVA", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "5-15 giorni lavorativi", 5, 15, destination_type="chamber_registry", blocking=["atto costitutivo mancante"], explanation="Ti accompagniamo nell'apertura della partita IVA per la tua societa."))

    entries.append(build_official("DEPOSITO_BILANCIO", "Deposito bilancio annuale", "Deposito del bilancio d'esercizio presso il Registro Imprese.", "societario", "Camera di Commercio", "deposito_bilancio", "Deposito bilancio", "Deposito telematico del bilancio d'esercizio approvato presso il Registro Imprese", "Pratica Telemaco / XBRL", URL_TELEMACO, "SPID", ["company"], ["ledger", "documents", "compliance", "flow"], ["company_documents", "accounting"], [DS_COMPANY, DS_BALANCE, DS_ASSEMBLY], "protocol_number", "Ricevuta deposito bilancio", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "5-15 giorni lavorativi", 5, 15, user_signs=True, delegation_possible=True, destination_type="chamber_registry", blocking=["bilancio non approvato dall'assemblea"], explanation="Prepariamo il deposito del bilancio d'esercizio presso la Camera di Commercio."))

    entries.append(build_official("NOMINA_AMMINISTRATORE", "Nomina/cambio amministratore", "Comunicazione di nomina o cambio amministratore al Registro Imprese.", "societario", "Camera di Commercio", "nomina_amministratore", "Nomina amministratore", "Deposito della comunicazione di nomina o cambio amministratore", "ComUnica / Modulo S2", URL_COMUNICA_STARWEB, "SPID", ["company"], ["research", "documents", "compliance", "flow"], ["company_documents", "identity"], [DS_COMPANY, DS_ASSEMBLY, DS_ID], "protocol_number", "Numero protocollo variazione", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "5-10 giorni lavorativi", 5, 10, user_signs=True, destination_type="chamber_registry", blocking=["verbale assemblea mancante"], explanation="Prepariamo la comunicazione di nomina o cambio amministratore presso la Camera di Commercio."))

    entries.append(build_official("MODIFICA_STATUTO", "Modifica statuto societario", "Deposito della modifica allo statuto della societa.", "societario", "Camera di Commercio", "modifica_statuto", "Modifica statuto", "Deposito dell'atto di modifica dello statuto sociale presso il Registro Imprese", "Atto notarile + ComUnica", URL_COMUNICA_STARWEB, "SPID", ["company"], ["research", "documents", "compliance", "flow", "routing"], ["company_documents", "identity"], [DS_STATUTO, DS_ASSEMBLY, DS_ID], "protocol_number", "Numero protocollo deposito", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "10-20 giorni lavorativi", 10, 20, user_signs=True, risk_level="high", destination_type="chamber_registry", blocking=["atto notarile mancante", "verbale assemblea straordinaria mancante"], explanation="Ti guidiamo nel deposito della modifica allo statuto societario presso il Registro Imprese."))

    entries.append(build_official("CESSIONE_QUOTE", "Cessione quote societarie", "Deposito dell'atto di cessione quote SRL.", "societario", "Camera di Commercio", "cessione_quote", "Cessione quote SRL", "Deposito dell'atto di trasferimento quote di SRL presso il Registro Imprese", "Atto notarile o commercialista", URL_COMUNICA_STARWEB, "SPID", ["company"], ["research", "documents", "compliance", "flow"], ["company_documents", "identity", "accounting"], [DS_COMPANY, DS_ID, DS_CONTRACT], "protocol_number", "Numero protocollo cessione", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "10-20 giorni lavorativi", 10, 20, user_signs=True, risk_level="high", destination_type="chamber_registry", blocking=["atto di cessione mancante", "consenso soci mancante"], explanation="Prepariamo la pratica di cessione quote SRL, verificando documentazione e requisiti."))

    entries.append(build_official("PEC_OBBLIGATORIA", "Comunicazione PEC obbligatoria", "Comunicazione o variazione dell'indirizzo PEC al Registro Imprese.", "societario", "Camera di Commercio", "comunicazione_pec", "Comunicazione PEC", "Deposito della comunicazione dell'indirizzo PEC obbligatorio presso il Registro Imprese", "ComUnica", URL_COMUNICA_STARWEB, "SPID", ["freelancer", "company"], ["documents", "flow"], ["identity"], [DS_ID], "protocol_number", "Conferma aggiornamento PEC", "immediate", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "1-5 giorni lavorativi", 1, 5, destination_type="chamber_registry", risk_level="basic", explanation="Ti aiutiamo a comunicare o aggiornare l'indirizzo PEC obbligatorio al Registro Imprese."))

    entries.append(build_official("ISCRIZIONE_REA", "Iscrizione REA", "Iscrizione al Repertorio Economico Amministrativo.", "societario", "Camera di Commercio", "iscrizione_rea", "Iscrizione REA", "Presentazione della denuncia REA per soggetti non iscritti al Registro Imprese", "Modulo REA", URL_COMUNICA_STARWEB, "SPID", ["freelancer"], ["research", "documents", "flow"], ["identity", "tax_declarations"], [DS_ID, DS_PIVA], "protocol_number", "Numero REA assegnato", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "5-10 giorni lavorativi", 5, 10, destination_type="chamber_registry", explanation="Ti guidiamo nell'iscrizione al REA per la tua attivita."))

    entries.append(build_official("TRASFORMAZIONE_SOCIETARIA", "Trasformazione societaria", "Gestione della trasformazione da una forma giuridica a un'altra.", "societario", "Camera di Commercio", "trasformazione_societa", "Trasformazione societaria", "Deposito dell'atto di trasformazione presso il Registro Imprese", "Atto notarile + ComUnica", URL_COMUNICA_STARWEB, "SPID", ["company"], ["intake", "research", "documents", "compliance", "flow", "routing"], ["company_documents", "identity", "accounting", "compliance"], [DS_COMPANY, DS_STATUTO, DS_BALANCE, DS_ID, DS_COMPLIANCE], "protocol_number", "Numero protocollo trasformazione", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "15-30 giorni lavorativi", 15, 30, user_signs=True, delegation_possible=True, risk_level="high", destination_type="chamber_registry", blocking=["atto notarile mancante", "situazione patrimoniale non aggiornata"], escalation=["strutture societarie complesse"], explanation="Ti accompagniamo nella trasformazione societaria, dalla preparazione dei documenti al deposito presso il Registro Imprese."))

    # ── LAVORO: +10 new (new category) ──

    entries.append(build_official("ASSUNZIONE_DIP", "Comunicazione assunzione dipendente", "Comunicazione obbligatoria di assunzione.", "lavoro", "Centro per l'Impiego", "comunicazione_assunzione", "Comunicazione assunzione", "Invio della comunicazione obbligatoria di assunzione tramite portale regionale", "Modello UniLav", None, "SPID", ["company"], ["research", "documents", "flow"], ["identity", "payroll"], [DS_ID, DS_EMPLOYEE, DS_WORK_CONTRACT], "protocol_number", "Numero protocollo comunicazione", "immediate", "portal_status", "Verifica stato comunicazione", None, "Entro il giorno precedente l'assunzione", 0, 1, destination_type="public_portal", url_verified=False, blocking=["contratto di lavoro non definito"], explanation="Ti guidiamo nell'invio della comunicazione obbligatoria di assunzione al Centro per l'Impiego."))

    entries.append(build_official("CESSAZIONE_DIP", "Comunicazione cessazione rapporto", "Comunicazione obbligatoria di cessazione del rapporto di lavoro.", "lavoro", "Centro per l'Impiego", "comunicazione_cessazione", "Comunicazione cessazione", "Invio della comunicazione obbligatoria di cessazione del rapporto di lavoro", "Modello UniLav", None, "SPID", ["company"], ["research", "documents", "flow"], ["identity", "payroll"], [DS_ID, DS_EMPLOYEE], "protocol_number", "Numero protocollo cessazione", "immediate", "portal_status", "Verifica stato comunicazione", None, "Entro 5 giorni dalla cessazione", 0, 5, destination_type="public_portal", url_verified=False, explanation="Ti guidiamo nella comunicazione obbligatoria di cessazione del rapporto di lavoro."))

    entries.append(build_official("TRASFORMAZIONE_CONTRATTO", "Trasformazione contratto di lavoro", "Comunicazione di trasformazione del rapporto di lavoro.", "lavoro", "Centro per l'Impiego", "trasformazione_contratto", "Trasformazione contratto", "Invio della comunicazione di trasformazione contrattuale (es. da determinato a indeterminato)", "Modello UniLav", None, "SPID", ["company"], ["research", "documents", "flow"], ["payroll"], [DS_EMPLOYEE, DS_WORK_CONTRACT], "protocol_number", "Numero protocollo trasformazione", "immediate", "portal_status", "Verifica stato comunicazione", None, "Entro 5 giorni dalla trasformazione", 0, 5, destination_type="public_portal", url_verified=False, explanation="Ti aiutiamo nella comunicazione di trasformazione del contratto di lavoro."))

    entries.append(build_official("BUSTA_PAGA", "Elaborazione buste paga", "Preparazione e verifica delle buste paga mensili.", "lavoro", "INPS", "elaborazione_buste_paga", "Elaborazione buste paga", "Calcolo retribuzioni, contributi e ritenute per la preparazione dei cedolini", "Cedolino paga", URL_INPS_SERVIZI, "SPID", ["company"], ["ledger", "compliance", "documents"], ["payroll"], [DS_PAYROLL, DS_EMPLOYEE], "portal_confirmation", "Cedolini elaborati", "immediate", "portal_status", "Verifica su portale paghe", None, "Mensile", 1, 5, destination_type="social_security", url_verified=False, explanation="Prepariamo e verifichiamo le buste paga mensili per i tuoi dipendenti."))

    entries.append(build_official("CONGUAGLIO_FISCALE", "Conguaglio fiscale di fine anno", "Calcolo e applicazione del conguaglio fiscale di fine anno.", "lavoro", "Agenzia delle Entrate", "conguaglio_fiscale", "Conguaglio fiscale", "Ricalcolo delle imposte e dei contributi in sede di conguaglio annuale", "Modello CU / Cedolino dicembre", URL_ADE_TELEMATICI, "SPID", ["company"], ["ledger", "compliance", "documents", "flow"], ["payroll", "accounting"], [DS_PAYROLL, DS_ACCOUNTING], "portal_confirmation", "Conguaglio applicato", "immediate", "receipt_verification", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "Dicembre - Febbraio", 1, 30, destination_type="tax_authority", url_verified=False, explanation="Calcoliamo il conguaglio fiscale di fine anno per i tuoi dipendenti."))

    # ── DOCUMENTALE: +5 new (7 → 12) ──

    entries.append(build_internal("DOC_ARCHIVE_DIGITAL", "Archiviazione digitale documenti", "Organizzazione e archiviazione digitale della documentazione.", "documentale", ["documents", "advisor"], explanation="Organizziamo e archiviamo in formato digitale la tua documentazione fiscale e amministrativa."))
    entries.append(build_internal("DOC_FIRMA_DIGITALE", "Supporto firma digitale", "Guida all'utilizzo della firma digitale sui documenti.", "documentale", ["documents", "advisor", "flow"], explanation="Ti guidiamo nell'utilizzo della firma digitale per documenti ufficiali e pratiche."))
    entries.append(build_internal("DOC_DELEGA_CASSETTO", "Preparazione delega cassetto fiscale", "Preparazione della delega per l'accesso al cassetto fiscale.", "documentale", ["documents", "flow", "advisor"], docs=["identity"], doc_specs=[DS_ID], approval=True, explanation="Prepariamo la delega per permettere a un intermediario di accedere al tuo cassetto fiscale."))
    entries.append(build_internal("DOC_LETTERA_INCARICO", "Preparazione lettera di incarico", "Redazione della lettera di incarico professionale.", "documentale", ["documents", "advisor"], approval=True, explanation="Prepariamo la lettera di incarico professionale per formalizzare il rapporto con il professionista."))
    entries.append(build_internal("DOC_PRIVACY_GDPR", "Documentazione privacy GDPR", "Preparazione della documentazione privacy e GDPR.", "documentale", ["documents", "compliance", "advisor"], explanation="Prepariamo la documentazione necessaria per la conformita al GDPR e alla normativa privacy."))

    # ── INFORMATIVO: +8 new (4 → 12) ──

    entries.append(build_internal("INFO_REGIME_ORDINARIO", "Informazioni regime ordinario", "Chiarimenti sul funzionamento del regime ordinario di contabilita.", "informativo", ["research", "advisor"], explanation="Spiegazione del regime ordinario: obblighi, registri, dichiarazioni e vantaggi rispetto ad altri regimi."))
    entries.append(build_internal("INFO_REGIME_SEMPLIFICATO", "Informazioni regime semplificato", "Chiarimenti su requisiti e funzionamento del regime semplificato.", "informativo", ["research", "advisor"], explanation="Spiegazione del regime semplificato: requisiti di accesso, obblighi e differenze con il regime ordinario."))
    entries.append(build_internal("INFO_APERTURA_ATTIVITA", "Orientamento apertura attivita", "Guida alla comprensione dei passi per avviare un'attivita.", "informativo", ["research", "advisor", "routing"], explanation="Ti aiutiamo a capire quali sono i passaggi necessari per avviare la tua attivita: P.IVA, iscrizioni, autorizzazioni."))
    entries.append(build_internal("INFO_CHIUSURA_ATTIVITA", "Orientamento chiusura attivita", "Guida ai passaggi per la chiusura di un'attivita.", "informativo", ["research", "advisor", "routing"], explanation="Ti spieghiamo i passaggi necessari per chiudere la tua attivita: obblighi fiscali, previdenziali e camerali."))
    entries.append(build_internal("INFO_DETRAZIONI", "Informazioni detrazioni fiscali", "Panoramica sulle detrazioni fiscali disponibili.", "informativo", ["research", "advisor"], explanation="Panoramica chiara sulle principali detrazioni fiscali: spese sanitarie, istruzione, ristrutturazioni, figli a carico."))
    entries.append(build_internal("INFO_BONUS_FISCALI", "Informazioni bonus e incentivi fiscali", "Chiarimenti su bonus e incentivi fiscali attivi.", "informativo", ["research", "advisor", "monitor"], explanation="Spiegazione dei bonus fiscali attivi: bonus edilizi, crediti d'imposta, incentivi per assunzioni."))
    entries.append(build_internal("INFO_SCADENZE_ANNUALI", "Calendario scadenze fiscali annuali", "Riepilogo delle principali scadenze fiscali dell'anno.", "informativo", ["research", "advisor", "deadline"], explanation="Ti forniamo il calendario delle scadenze fiscali annuali con date e adempimenti principali."))
    entries.append(build_internal("INFO_RESPONSABILITA_FISCALE", "Responsabilita fiscale e rischi", "Chiarimenti sulle responsabilita fiscali e i rischi connessi.", "informativo", ["research", "advisor"], explanation="Spiegazione delle responsabilita fiscali dell'imprenditore e dei rischi in caso di inadempimento."))

    # ══════════════════════════════════════════════════════════════
    # BATCH 2 EXPANSION — NEW PROCEDURES (78 → 123)
    # ══════════════════════════════════════════════════════════════

    # ── FISCALE: +6 (24 → 30) ──

    entries.append(build_official("ESTEROMETRO", "Comunicazione operazioni transfrontaliere", "Invio della comunicazione delle operazioni transfrontaliere (ex Esterometro).", "fiscale", "Agenzia delle Entrate", "invio_esterometro", "Comunicazione dati fatture estere", "Trasmissione telematica dei dati delle operazioni con soggetti non residenti", "Fatturazione elettronica transfrontaliera", URL_ADE_TELEMATICI, "SPID", ["freelancer", "company"], ["ledger", "documents", "compliance", "flow"], ["accounting", "vat_documents"], [DS_ACCOUNTING, DS_VAT_REGS], "protocol_number", "Ricevuta trasmissione dati transfrontalieri", "immediate", "portal_status", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "1-3 giorni lavorativi", 1, 3, explanation="Prepariamo e inviamo la comunicazione delle operazioni con l'estero tramite fatturazione elettronica."))

    entries.append(build_official("ISA_AFFIDABILITA", "Indici sintetici di affidabilita fiscale (ISA)", "Compilazione e trasmissione degli ISA.", "fiscale", "Agenzia delle Entrate", "trasmissione_isa", "Trasmissione ISA", "Compilazione e invio telematico degli Indici sintetici di affidabilita fiscale", "Modello ISA", URL_ADE_TELEMATICI, "SPID", ["freelancer", "company"], ["ledger", "compliance", "documents", "flow", "advisor"], ["accounting"], [DS_ACCOUNTING], "protocol_number", "Ricevuta ISA", "delayed", "portal_status", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "5-10 giorni lavorativi", 5, 10, user_signs=True, delegation_possible=True, explanation="Calcoliamo e trasmettiamo gli ISA, gli indici sintetici di affidabilita fiscale che misurano la tua posizione."))

    entries.append(build_official("IMPOSTA_BOLLO_EFATT", "Versamento imposta di bollo su e-fatture", "Calcolo e versamento dell'imposta di bollo sulle fatture elettroniche.", "fiscale", "Agenzia delle Entrate", "versamento_bollo_efatt", "Versamento imposta di bollo", "Calcolo trimestrale e versamento dell'imposta di bollo dovuta sulle e-fatture", "Modello F24 / Addebito diretto", URL_ADE_TELEMATICI, "SPID", ["freelancer", "company"], ["ledger", "compliance"], ["accounting"], [DS_ACCOUNTING], "payment_receipt", "Quietanza versamento bollo", "immediate", "receipt_verification", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "Trimestrale", 1, 3, explanation="Calcoliamo l'imposta di bollo dovuta sulle fatture elettroniche e prepariamo il versamento."))

    entries.append(build_official("BONUS_EDILIZI", "Comunicazione bonus edilizi / Superbonus", "Comunicazione opzione cessione credito o sconto in fattura per bonus edilizi.", "fiscale", "Agenzia delle Entrate", "comunicazione_bonus_edilizi", "Comunicazione opzione bonus edilizi", "Invio della comunicazione di opzione per cessione del credito o sconto in fattura", "Comunicazione opzione", URL_ADE_TELEMATICI, "SPID", ["private", "freelancer", "company"], ["research", "documents", "compliance", "flow", "advisor"], ["accounting", "identity"], [DS_ACCOUNTING, DS_ID, DS_PROPERTY], "protocol_number", "Ricevuta comunicazione opzione", "delayed", "portal_status", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "5-15 giorni lavorativi", 5, 15, risk_level="high", user_signs=True, blocking=["documentazione intervento incompleta", "asseverazione tecnica mancante"], explanation="Ti guidiamo nella comunicazione delle opzioni per i bonus edilizi, verificando requisiti e documentazione."))

    entries.append(build_official("CREDITO_IMPOSTA_RS", "Credito d'imposta ricerca e sviluppo", "Richiesta del credito d'imposta per attivita di ricerca e sviluppo.", "fiscale", "Agenzia delle Entrate", "richiesta_credito_rs", "Credito d'imposta R&S", "Compilazione e invio della comunicazione per il credito d'imposta R&S", "Modello RSM", URL_ADE_TELEMATICI, "SPID", ["company"], ["research", "ledger", "documents", "compliance", "flow", "advisor"], ["accounting"], [DS_ACCOUNTING, {"key": "rs_documentation", "name": "Documentazione attivita R&S", "why_needed": "Per dimostrare le attivita di ricerca e sviluppo svolte", "format": "Relazione tecnica + costi", "mandatory": True}], "protocol_number", "Ricevuta comunicazione credito R&S", "delayed", "portal_status", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "30-60 giorni lavorativi", 30, 60, risk_level="high", user_signs=True, delegation_possible=True, blocking=["documentazione tecnica R&S mancante"], explanation="Prepariamo la richiesta di credito d'imposta per le tue attivita di ricerca e sviluppo."))

    entries.append(build_official("IMPOSTA_REGISTRO", "Registrazione atto e imposta di registro", "Registrazione di atti e versamento imposta di registro presso AdE.", "fiscale", "Agenzia delle Entrate", "registrazione_atto", "Registrazione atto", "Registrazione telematica di atti soggetti a imposta di registro", "Modello 69 / RAP", URL_ADE_TELEMATICI, "SPID", ["private", "freelancer", "company"], ["research", "documents", "flow"], ["identity"], [DS_ID, DS_CONTRACT], "protocol_number", "Ricevuta registrazione atto", "immediate", "portal_status", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "1-5 giorni lavorativi", 1, 5, explanation="Ti guidiamo nella registrazione dell'atto e nel versamento dell'imposta di registro."))

    # ── PREVIDENZIALE: +5 (12 → 17) ──

    entries.append(build_official("INPS_RISCATTO_LAUREA", "Domanda riscatto laurea INPS", "Presentazione domanda di riscatto del periodo di laurea ai fini pensionistici.", "previdenziale", "INPS", "domanda_riscatto_laurea", "Domanda riscatto laurea", "Presentazione telematica della domanda di riscatto del periodo universitario", "Domanda online INPS", URL_INPS_SERVIZI, "SPID", ["private", "freelancer"], ["research", "documents", "flow", "advisor"], ["identity"], [DS_ID, {"key": "laurea_docs", "name": "Certificato di laurea", "why_needed": "Per dimostrare il periodo universitario da riscattare", "format": "Certificato PDF", "mandatory": True}], "protocol_number", "Conferma domanda riscatto", "delayed", "portal_status", "Verifica stato su MyINPS", URL_INPS_MYINPS, "30-90 giorni lavorativi", 30, 90, risk_level="high", destination_type="social_security", explanation="Ti guidiamo nella domanda di riscatto della laurea per fini pensionistici."))

    entries.append(build_official("INPS_RICONGIUNZIONE", "Ricongiunzione contributi INPS", "Domanda di ricongiunzione dei periodi contributivi.", "previdenziale", "INPS", "domanda_ricongiunzione", "Domanda ricongiunzione", "Presentazione telematica della domanda di ricongiunzione dei contributi versati a gestioni diverse", "Domanda online INPS", URL_INPS_SERVIZI, "SPID", ["private", "freelancer"], ["research", "documents", "flow"], ["identity"], [DS_ID], "protocol_number", "Conferma domanda ricongiunzione", "delayed", "portal_status", "Verifica stato su MyINPS", URL_INPS_MYINPS, "60-120 giorni lavorativi", 60, 120, risk_level="high", destination_type="social_security", explanation="Ti aiutiamo a presentare la domanda di ricongiunzione dei contributi versati a gestioni previdenziali diverse."))

    entries.append(build_official("INPS_ESTRATTO_CONTO", "Verifica estratto conto contributivo", "Consultazione e verifica dell'estratto conto contributivo INPS.", "previdenziale", "INPS", "verifica_estratto_conto", "Verifica estratto conto", "Accesso e verifica dell'estratto conto contributivo per verifica della posizione previdenziale", "MyINPS", URL_INPS_MYINPS, "SPID", ["private", "freelancer", "company"], ["research", "advisor"], ["identity"], [DS_ID], "portal_confirmation", "Estratto conto consultato", "immediate", "portal_status", "Verifica su MyINPS", URL_INPS_MYINPS, "Immediato", 0, 1, risk_level="basic", destination_type="social_security", explanation="Verifichiamo insieme il tuo estratto conto contributivo per accertare che la tua posizione sia corretta."))

    entries.append(build_official("INPS_BONUS_NIDO", "Domanda bonus asilo nido", "Presentazione domanda bonus asilo nido INPS.", "previdenziale", "INPS", "domanda_bonus_nido", "Domanda bonus nido", "Presentazione telematica della domanda di contributo per le rette degli asili nido", "Domanda online INPS", URL_INPS_SERVIZI, "SPID", ["private", "freelancer"], ["research", "documents", "flow"], ["identity"], [DS_ID, {"key": "nido_docs", "name": "Documentazione asilo e ISEE", "why_needed": "Per dimostrare la frequenza e il diritto al contributo", "format": "Ricevute iscrizione + ISEE", "mandatory": True}], "protocol_number", "Conferma domanda bonus nido", "delayed", "portal_status", "Verifica stato su MyINPS", URL_INPS_MYINPS, "15-30 giorni lavorativi", 15, 30, destination_type="social_security", explanation="Ti guidiamo nella domanda del bonus asilo nido, raccogliendo la documentazione necessaria."))

    entries.append(build_official("INPS_CONGEDO_PARENTALE", "Domanda congedo parentale", "Presentazione domanda di congedo parentale facoltativo.", "previdenziale", "INPS", "domanda_congedo_parentale", "Domanda congedo parentale", "Presentazione telematica della domanda di congedo parentale facoltativo", "Domanda online INPS", URL_INPS_SERVIZI, "SPID", ["private", "freelancer"], ["research", "documents", "flow"], ["identity"], [DS_ID, DS_EMPLOYEE], "protocol_number", "Conferma domanda congedo", "delayed", "portal_status", "Verifica stato su MyINPS", URL_INPS_MYINPS, "10-30 giorni lavorativi", 10, 30, destination_type="social_security", explanation="Ti aiutiamo nella presentazione della domanda di congedo parentale facoltativo all'INPS."))

    # ── SOCIETARIO: +5 (13 → 18) ──

    entries.append(build_official("VIDIMAZIONE_LIBRI", "Vidimazione libri sociali", "Vidimazione dei libri sociali obbligatori presso la Camera di Commercio.", "societario", "Camera di Commercio", "vidimazione_libri", "Vidimazione libri", "Presentazione dei libri sociali per la vidimazione presso la CCIAA", "Richiesta vidimazione", URL_COMUNICA_STARWEB, "SPID", ["company"], ["documents", "flow"], ["company_documents"], [DS_COMPANY], "receipt_code", "Ricevuta vidimazione", "immediate", "receipt_verification", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "1-3 giorni lavorativi", 1, 3, destination_type="chamber_registry", risk_level="basic", explanation="Ti guidiamo nella vidimazione dei libri sociali obbligatori presso la Camera di Commercio."))

    entries.append(build_official("DOMICILIAZIONE_LEGALE", "Comunicazione domiciliazione legale", "Comunicazione di domiciliazione della sede legale al Registro Imprese.", "societario", "Camera di Commercio", "domiciliazione_legale", "Domiciliazione sede legale", "Deposito della comunicazione di domiciliazione legale tramite ComUnica", "ComUnica / Modulo S5", URL_COMUNICA_STARWEB, "SPID", ["company"], ["research", "documents", "flow"], ["company_documents", "identity"], [DS_COMPANY, DS_ID, DS_CONTRACT], "protocol_number", "Numero protocollo domiciliazione", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "5-10 giorni lavorativi", 5, 10, destination_type="chamber_registry", explanation="Ti guidiamo nella comunicazione della domiciliazione legale della sede societaria."))

    entries.append(build_official("CONTRATTO_RETE", "Iscrizione contratto di rete", "Iscrizione del contratto di rete tra imprese al Registro Imprese.", "societario", "Camera di Commercio", "iscrizione_contratto_rete", "Iscrizione contratto di rete", "Deposito del contratto di rete tra imprese presso il Registro Imprese", "ComUnica", URL_COMUNICA_STARWEB, "SPID", ["company"], ["research", "documents", "compliance", "flow"], ["company_documents", "identity"], [DS_COMPANY, DS_CONTRACT, DS_ID], "protocol_number", "Numero protocollo iscrizione rete", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "10-20 giorni lavorativi", 10, 20, destination_type="chamber_registry", url_verified=False, explanation="Ti accompagniamo nell'iscrizione del contratto di rete tra imprese al Registro."))

    entries.append(build_official("SCIOGLIMENTO_SOCIETA", "Scioglimento anticipato societa", "Procedura di scioglimento anticipato e messa in liquidazione.", "societario", "Camera di Commercio", "scioglimento_societa", "Scioglimento societa", "Deposito dell'atto di scioglimento anticipato e nomina liquidatore presso il Registro Imprese", "Atto notarile + ComUnica", URL_COMUNICA_STARWEB, "SPID", ["company"], ["intake", "research", "documents", "compliance", "flow", "routing"], ["company_documents", "identity", "accounting"], [DS_COMPANY, DS_STATUTO, DS_BALANCE, DS_ASSEMBLY, DS_ID], "protocol_number", "Numero protocollo scioglimento", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "15-30 giorni lavorativi", 15, 30, user_signs=True, risk_level="high", destination_type="chamber_registry", blocking=["delibera assembleare mancante", "situazione patrimoniale non aggiornata"], escalation=["societa con debiti pendenti"], explanation="Ti accompagniamo nella procedura di scioglimento anticipato e messa in liquidazione della societa."))

    entries.append(build_official("FUSIONE_SOCIETARIA", "Fusione societaria", "Gestione della procedura di fusione tra societa.", "societario", "Camera di Commercio", "fusione_societaria", "Fusione societaria", "Deposito del progetto di fusione e atti correlati presso il Registro Imprese", "Progetto fusione + ComUnica", URL_COMUNICA_STARWEB, "SPID", ["company"], ["intake", "research", "documents", "compliance", "flow", "routing"], ["company_documents", "identity", "accounting", "compliance"], [DS_COMPANY, DS_STATUTO, DS_BALANCE, DS_ASSEMBLY, DS_ID, DS_COMPLIANCE], "protocol_number", "Numero protocollo fusione", "delayed", "portal_status", "Verifica su Registro Imprese", URL_REGISTRO_IMPRESE, "30-90 giorni lavorativi", 30, 90, user_signs=True, delegation_possible=True, risk_level="high", destination_type="chamber_registry", blocking=["progetto di fusione non depositato", "opposizione creditori pendente"], escalation=["fusioni transfrontaliere", "strutture societarie complesse"], explanation="Ti guidiamo nell'intera procedura di fusione societaria, dal progetto al deposito finale."))

    # ── LAVORO: +10 (5 → 15) ──

    entries.append(build_official("PROSPETTO_INFORMATIVO", "Invio prospetto informativo disabili", "Invio del prospetto informativo per il collocamento obbligatorio.", "lavoro", "Centro per l'Impiego", "invio_prospetto_informativo", "Prospetto informativo", "Trasmissione telematica del prospetto informativo per il collocamento mirato dei disabili", "Prospetto informativo online", None, "SPID", ["company"], ["ledger", "documents", "compliance", "flow"], ["payroll"], [DS_PAYROLL, DS_EMPLOYEE], "protocol_number", "Ricevuta prospetto", "immediate", "portal_status", "Verifica stato comunicazione", None, "Entro il 31 gennaio", 0, 5, destination_type="public_portal", url_verified=False, explanation="Prepariamo e inviamo il prospetto informativo per il collocamento obbligatorio dei lavoratori disabili."))

    entries.append(build_official("LIBRO_UNICO", "Gestione Libro Unico del Lavoro", "Tenuta e aggiornamento del Libro Unico del Lavoro (LUL).", "lavoro", "Ispettorato del Lavoro", "gestione_lul", "Libro Unico del Lavoro", "Tenuta, compilazione e conservazione del Libro Unico del Lavoro obbligatorio", "LUL", None, "SPID", ["company"], ["ledger", "documents", "compliance"], ["payroll"], [DS_PAYROLL, DS_EMPLOYEE], "portal_confirmation", "LUL aggiornato", "immediate", "receipt_verification", "Verifica conformita", None, "Mensile", 1, 5, destination_type="public_portal", url_verified=False, risk_level="basic", explanation="Gestiamo la tenuta e l'aggiornamento del Libro Unico del Lavoro per la tua azienda."))

    entries.append(build_official("WELFARE_AZIENDALE", "Piano welfare aziendale", "Strutturazione e comunicazione del piano di welfare aziendale.", "lavoro", "Agenzia delle Entrate", "piano_welfare", "Piano welfare aziendale", "Strutturazione del piano welfare e comunicazione dei benefit ai dipendenti secondo la normativa vigente", "Regolamento welfare", URL_ADE_TELEMATICI, "SPID", ["company"], ["research", "documents", "advisor", "compliance"], ["payroll", "accounting"], [DS_PAYROLL, DS_ACCOUNTING], "portal_confirmation", "Piano welfare registrato", "delayed", "portal_status", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "15-30 giorni lavorativi", 15, 30, destination_type="tax_authority", url_verified=False, explanation="Ti guidiamo nella strutturazione e comunicazione del piano di welfare aziendale per i tuoi dipendenti."))

    entries.append(build_official("CU_DIPENDENTI", "Certificazione Unica dipendenti", "Compilazione e invio delle CU per i dipendenti.", "lavoro", "Agenzia delle Entrate", "invio_cu_dipendenti", "Invio CU dipendenti", "Compilazione e trasmissione telematica delle Certificazioni Uniche per i lavoratori dipendenti", "Modello CU", URL_ADE_TELEMATICI, "SPID", ["company"], ["ledger", "documents", "compliance", "flow"], ["payroll"], [DS_PAYROLL], "protocol_number", "Ricevuta CU dipendenti", "delayed", "portal_status", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "Entro il 16 marzo", 1, 10, user_signs=True, delegation_possible=True, explanation="Prepariamo e inviamo le Certificazioni Uniche per tutti i tuoi dipendenti."))

    entries.append(build_official("MOD_770_SOSTITUTI", "Modello 770 sostituti d'imposta", "Compilazione e invio del 770 come sostituto d'imposta per i dipendenti.", "lavoro", "Agenzia delle Entrate", "invio_770_sostituti", "Invio 770 sostituti", "Trasmissione telematica del Modello 770 con i dati delle ritenute operate sui dipendenti", "Modello 770", URL_ADE_TELEMATICI, "SPID", ["company"], ["ledger", "documents", "compliance", "flow"], ["payroll", "accounting"], [DS_PAYROLL, DS_ACCOUNTING], "protocol_number", "Ricevuta 770 sostituti", "delayed", "portal_status", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "Entro il 31 ottobre", 5, 15, user_signs=True, delegation_possible=True, explanation="Prepariamo il Modello 770 per la dichiarazione delle ritenute operate come sostituto d'imposta."))

    entries.append(build_official("FRINGE_BENEFIT", "Gestione fringe benefit", "Calcolo e comunicazione dei fringe benefit aziendali.", "lavoro", "Agenzia delle Entrate", "gestione_fringe_benefit", "Gestione fringe benefit", "Calcolo del valore dei fringe benefit e relativa comunicazione ai fini fiscali e contributivi", "Cedolino / CU", URL_ADE_TELEMATICI, "SPID", ["company"], ["ledger", "compliance", "advisor"], ["payroll", "accounting"], [DS_PAYROLL, DS_ACCOUNTING], "portal_confirmation", "Fringe benefit calcolati", "immediate", "receipt_verification", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "Annuale", 1, 5, destination_type="tax_authority", url_verified=False, explanation="Calcoliamo il valore dei fringe benefit per i tuoi dipendenti e ne gestiamo la comunicazione fiscale."))

    entries.append(build_official("GESTIONE_FERIE", "Gestione ferie e permessi", "Monitoraggio e gestione dei residui ferie e permessi dei dipendenti.", "lavoro", "INPS", "gestione_ferie_permessi", "Gestione ferie e permessi", "Monitoraggio dei residui ferie e permessi, calcolo indennita per ferie non godute", "Cedolino paga", URL_INPS_SERVIZI, "SPID", ["company"], ["ledger", "compliance", "documents"], ["payroll"], [DS_PAYROLL], "portal_confirmation", "Report ferie aggiornato", "immediate", "portal_status", "Verifica su portale paghe", None, "Mensile", 1, 5, destination_type="social_security", url_verified=False, risk_level="basic", explanation="Monitoriamo e gestiamo i residui ferie e permessi per i tuoi dipendenti."))

    entries.append(build_official("TRASFERTA_RIMBORSO", "Gestione trasferte e rimborsi", "Calcolo e gestione delle trasferte e dei rimborsi spese.", "lavoro", "Agenzia delle Entrate", "gestione_trasferte", "Gestione trasferte", "Calcolo delle indennita di trasferta e gestione dei rimborsi spese secondo normativa fiscale", "Nota spese / Cedolino", URL_ADE_TELEMATICI, "SPID", ["company"], ["ledger", "compliance", "advisor"], ["payroll", "accounting"], [DS_PAYROLL, DS_ACCOUNTING], "portal_confirmation", "Trasferte registrate", "immediate", "receipt_verification", "Verifica contabile", None, "Mensile", 1, 5, destination_type="tax_authority", url_verified=False, risk_level="basic", explanation="Gestiamo il calcolo delle trasferte e dei rimborsi spese nel rispetto della normativa fiscale."))

    entries.append(build_official("PREMIO_RISULTATO", "Premio di risultato e detassazione", "Gestione del premio di risultato con detassazione agevolata.", "lavoro", "Agenzia delle Entrate", "premio_risultato", "Premio di risultato", "Calcolo e applicazione del premio di risultato con imposta sostitutiva agevolata al 10%", "Cedolino / CU", URL_ADE_TELEMATICI, "SPID", ["company"], ["ledger", "compliance", "advisor", "documents"], ["payroll", "accounting"], [DS_PAYROLL, DS_ACCOUNTING, {"key": "accordo_produttivita", "name": "Accordo di produttivita", "why_needed": "Per applicare la detassazione prevista dalla normativa", "format": "PDF accordo aziendale o territoriale", "mandatory": True}], "portal_confirmation", "Premio applicato con detassazione", "immediate", "receipt_verification", "Verifica nel cassetto fiscale", URL_ADE_CASSETTO, "Annuale", 1, 5, destination_type="tax_authority", url_verified=False, explanation="Gestiamo il premio di risultato per i tuoi dipendenti con l'applicazione della detassazione agevolata."))

    entries.append(build_official("CEDOLINO_COLLABORATORE", "Cedolino collaboratore / co.co.co.", "Elaborazione del cedolino per collaboratori coordinati e continuativi.", "lavoro", "INPS", "cedolino_collaboratore", "Cedolino collaboratore", "Elaborazione del cedolino paga per collaboratori co.co.co. con calcolo contributi e ritenute", "Cedolino co.co.co.", URL_INPS_SERVIZI, "SPID", ["company"], ["ledger", "documents", "compliance"], ["payroll"], [DS_PAYROLL, DS_EMPLOYEE], "portal_confirmation", "Cedolino elaborato", "immediate", "portal_status", "Verifica su MyINPS", URL_INPS_MYINPS, "Mensile", 1, 5, destination_type="social_security", url_verified=False, explanation="Elaboriamo il cedolino per i collaboratori co.co.co. con calcolo di contributi e ritenute."))

    # ── DOCUMENTALE: +8 (12 → 20) ──

    entries.append(build_internal("DOC_CONSERVAZIONE_SOST", "Conservazione sostitutiva documenti", "Attivazione e gestione della conservazione sostitutiva a norma.", "documentale", ["documents", "compliance"], explanation="Attiviamo la conservazione sostitutiva dei documenti digitali secondo la normativa vigente."))
    entries.append(build_internal("DOC_MARCA_TEMPORALE", "Apposizione marca temporale", "Guida all'apposizione della marca temporale sui documenti.", "documentale", ["documents", "advisor"], explanation="Ti guidiamo nell'apposizione della marca temporale per garantire la validita legale dei documenti."))
    entries.append(build_internal("DOC_PROCURA_TELEMATICA", "Preparazione procura telematica", "Predisposizione della procura per l'invio telematico.", "documentale", ["documents", "flow", "advisor"], docs=["identity"], doc_specs=[DS_ID], approval=True, explanation="Prepariamo la procura telematica per autorizzare un intermediario all'invio delle tue pratiche."))
    entries.append(build_internal("DOC_RACCOLTA_CONSENSI", "Raccolta consensi e autorizzazioni", "Raccolta dei consensi e delle autorizzazioni necessarie.", "documentale", ["documents", "compliance"], explanation="Organizziamo la raccolta dei consensi e delle autorizzazioni necessarie per le tue pratiche."))
    entries.append(build_internal("DOC_CONTRATTO_SERVIZIO", "Preparazione contratto di servizio", "Redazione del contratto di servizio professionale.", "documentale", ["documents", "advisor"], approval=True, explanation="Redigiamo il contratto di servizio professionale per formalizzare le condizioni di collaborazione."))
    entries.append(build_internal("DOC_CHECKLIST_ANNUALE", "Checklist adempimenti annuali", "Preparazione della checklist completa degli adempimenti annuali.", "documentale", ["documents", "advisor", "deadline"], explanation="Prepariamo una checklist personalizzata con tutti gli adempimenti annuali da rispettare per la tua attivita."))
    entries.append(build_internal("DOC_FASCICOLO_CLIENTI", "Gestione fascicolo cliente", "Organizzazione e aggiornamento del fascicolo documentale del cliente.", "documentale", ["documents", "compliance"], explanation="Organizziamo e manteniamo aggiornato il tuo fascicolo documentale per una gestione ordinata e completa."))
    entries.append(build_internal("DOC_TEMPLATE_FATTURA", "Preparazione template fattura", "Creazione del template personalizzato per la fatturazione.", "documentale", ["documents", "advisor"], explanation="Creiamo un template personalizzato per le tue fatture, conforme ai requisiti della fatturazione elettronica."))

    # ── INFORMATIVO: +11 (12 → 23) ──

    entries.append(build_internal("INFO_CONTRIBUTI_MINIMI", "Informazioni contributi minimi obbligatori", "Chiarimenti sui contributi minimi da versare per ogni gestione.", "informativo", ["research", "advisor"], explanation="Spiegazione dei contributi minimi obbligatori previsti per le diverse gestioni previdenziali."))
    entries.append(build_internal("INFO_DEDUZIONI", "Informazioni deduzioni fiscali", "Panoramica sulle deduzioni fiscali disponibili per ridurre l'imponibile.", "informativo", ["research", "advisor"], explanation="Panoramica sulle principali deduzioni fiscali: fondi pensione, contributi previdenziali, spese sanitarie integrative."))
    entries.append(build_internal("INFO_SCADENZE_TRIMESTRALI", "Calendario scadenze trimestrali", "Riepilogo delle scadenze fiscali e contributive per il trimestre.", "informativo", ["research", "advisor", "deadline"], explanation="Ti forniamo il calendario aggiornato delle scadenze trimestrali: IVA, LIPE, contributi, comunicazioni."))
    entries.append(build_internal("INFO_FATTURAZIONE_ELETTRONICA", "Guida alla fatturazione elettronica", "Informazioni su obblighi e funzionamento della fatturazione elettronica.", "informativo", ["research", "advisor"], explanation="Spiegazione degli obblighi di fatturazione elettronica: SdI, formati, conservazione, tempistiche."))
    entries.append(build_internal("INFO_REGIME_IMPATRIATI", "Informazioni regime fiscale impatriati", "Chiarimenti sulle agevolazioni per i lavoratori impatriati.", "informativo", ["research", "advisor"], explanation="Spiegazione delle agevolazioni fiscali per i lavoratori che trasferiscono la residenza in Italia."))
    entries.append(build_internal("INFO_STARTUP_INNOVATIVA", "Informazioni startup innovativa", "Chiarimenti su requisiti e vantaggi delle startup innovative.", "informativo", ["research", "advisor"], explanation="Panoramica sui requisiti per qualificarsi come startup innovativa e i relativi vantaggi fiscali e societari."))
    entries.append(build_internal("INFO_SOCIETA_BENEFIT", "Informazioni societa benefit", "Chiarimenti sulle societa benefit e il loro regime.", "informativo", ["research", "advisor"], explanation="Spiegazione del modello delle societa benefit: requisiti, obblighi di trasparenza e vantaggi reputazionali."))
    entries.append(build_internal("INFO_OBBLIGO_PEC", "Informazioni obbligo PEC", "Chiarimenti sull'obbligo di PEC per imprese e professionisti.", "informativo", ["research", "advisor"], explanation="Spiegazione dell'obbligo di possedere un indirizzo PEC per imprese e professionisti iscritti."))
    entries.append(build_internal("INFO_ANTIRIC_ADEGUATA", "Informazioni adeguata verifica antiriciclaggio", "Chiarimenti sugli obblighi di adeguata verifica della clientela.", "informativo", ["research", "advisor", "compliance"], explanation="Spiegazione degli obblighi di adeguata verifica della clientela previsti dalla normativa antiriciclaggio."))
    entries.append(build_internal("INFO_PIANIFICAZIONE_SUCCESSORIA", "Orientamento pianificazione successoria", "Guida alla pianificazione successoria e patrimoniale.", "informativo", ["research", "advisor"], explanation="Orientamento sulla pianificazione successoria: strumenti disponibili, implicazioni fiscali e passaggi consigliati."))
    entries.append(build_internal("INFO_LAVORO_AUTONOMO", "Informazioni lavoro autonomo occasionale", "Chiarimenti sul lavoro autonomo occasionale e relativi obblighi.", "informativo", ["research", "advisor"], explanation="Spiegazione del lavoro autonomo occasionale: limiti, obblighi di comunicazione, ritenuta d'acconto e contributi."))

    return entries
